name: Linux tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linux-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init

    - name: Setup env
      run: python3 -m venv ${{github.workspace}}/venv

    - name: Install dependencies
      run: ${{github.workspace}}/venv/bin/python3 -m pip install -r ${{github.workspace}}/requirements.txt

    - name: Run tests
      run: ${{github.workspace}}/venv/bin/python3 -m unittest discover ${{github.workspace}}/test
